Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-03, with the labels that each got.

#2876 chore: Update setup.py
  setup.py
Labels: Community want to contribute

#2862 Update quantization/README.md
  examples/quantization/README.md
Labels: Community want to contribute

#3003 fix: Fix path to constraints.txt in bloom/requirements.txt
  examples/models/contrib/bloom/requirements.txt
Labels: Community want to contribute

#3100 CI: Waive for https://nvbugspro.nvidia.com/bug/5189673
  tests/unittest/_torch/multi_gpu_modeling/test_deepseek.py
Labels: bug, CI

#3027 test: [TRTLLM-4000] Port multi GPU changes to GitHub
  cpp/tests/executor/executorTest.cpp
  tests/integration/defs/cpp_common.py
  tests/integration/defs/test_cpp.py
  tests/integration/test_lists/test-db/l0_dgx_h100.yml
Labels: CI

#3113 fix: Early exit cmake if find_library() does not find any lib
  cpp/cmake/modules/find_library_create_target.cmake
Labels: Community want to contribute

#3153 doc: use alert formatting
  examples/deepseek_v3/README.md
  examples/enc_dec/README.md
Labels: Community want to contribute

#2768 fix: Add missing parameter for WeightOnlyQuantRowLinear module
  tensorrt_llm/quantization/layers.py
Labels: triaged, Community want to contribute
