Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-05, with the labels that each got.

#3354 feat: add deepseek-r1 reasoning parser to trtllm-serve
  examples/serve/deepseek_r1_reasoning_parser.sh
  tensorrt_llm/commands/serve.py
  tensorrt_llm/llmapi/llm_args.py
  tensorrt_llm/llmapi/reasoning_parser.py
  tensorrt_llm/serve/openai_protocol.py
  tensorrt_llm/serve/openai_server.py
  tensorrt_llm/serve/postprocess_handlers.py
  tests/integration/defs/test_e2e.py
  tests/integration/test_lists/test-db/l0_a10.yml
  tests/unittest/llmapi/apps/_test_openai_reasoning.py
  tests/unittest/llmapi/test_reasoning_parser.py
Labels: Community want to contribute, Community Engagement

#4097 enh: Update docker Makefile to use only the visible GPUs of machine
  docker/Makefile
Labels: Ease of Use

#4089 [#4085][fix] Fix `apply_per_channel_scale` for extremely large input sequence length.
  cpp/tensorrt_llm/kernels/preQuantScaleKernel.cu
  cpp/tensorrt_llm/kernels/preQuantScaleKernel.h
Labels: bug

#4066 feat: Support the Structural Tag in guided decoding
  cpp/include/tensorrt_llm/executor/executor.h
  cpp/tensorrt_llm/pybind/executor/request.cpp
  tensorrt_llm/_torch/pyexecutor/_util.py
  tensorrt_llm/_torch/pyexecutor/guided_decoder.py
  tensorrt_llm/sampling_params.py
  tensorrt_llm/serve/openai_protocol.py
  tests/integration/defs/test_e2e.py
  tests/integration/test_lists/test-db/l0_a10.yml
  tests/unittest/api_stability/references/guided_decoding_params.yaml
  tests/unittest/llmapi/apps/_test_openai_chat_structural_tag.py
Labels: Community want to contribute, Community Engagement

#3283 feat:[AutoDeploy] Update MoE pattern matcher to drop expert selection logic
  tensorrt_llm/_torch/auto_deploy/custom_ops/fused_moe.py
  tensorrt_llm/_torch/auto_deploy/models/deepseek.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/fused_moe.py
Labels: AutoDeploy

#4365 [AutoDeploy] fix: disable overlap scheduler until supported
  tensorrt_llm/_torch/auto_deploy/shim/interface.py
Labels: AutoDeploy

#4240 [AutoDeploy]feat: Add an AutoDeploy compile backend that only calls torch.compile
  examples/auto_deploy/README.md
  examples/auto_deploy/build_and_run_ad.py
  examples/auto_deploy/simple_config.py
  tensorrt_llm/_torch/auto_deploy/compile/backends/__init__.py
  tensorrt_llm/_torch/auto_deploy/compile/backends/torch_compile.py
  tensorrt_llm/_torch/auto_deploy/compile/backends/torch_cudagraph.py
  tensorrt_llm/_torch/auto_deploy/compile/backends/torch_opt.py
  tensorrt_llm/_torch/auto_deploy/compile/compiler.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/compile/test_captured_graph.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/compile/test_compiler.py
Labels: AutoDeploy

#4372 [AutoDeploy] configurable cache resize
  examples/auto_deploy/build_and_run_ad.py
  examples/auto_deploy/simple_config.py
  tensorrt_llm/_torch/auto_deploy/shim/interface.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tests/unittest/_torch/auto_deploy/integration/test_ad_build.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/test_ad_build_small_multi.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
Labels: AutoDeploy

#4373 [AutoDeploy] fix: proper process group clean up
  tensorrt_llm/_torch/auto_deploy/distributed/common.py
  tensorrt_llm/_torch/auto_deploy/shim/demollm.py
Labels: AutoDeploy

#4370 [AutoDeploy] eager pattern matcher new pattern
  tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_attention_matcher.py
Labels: AutoDeploy

#3439 perf: Eliminate the need for attention DP padding when possible
  cpp/tensorrt_llm/thop/allgatherOp.cpp
  cpp/tensorrt_llm/thop/reducescatterOp.cpp
  tensorrt_llm/_torch/auto_deploy/custom_ops/dist.py
  tensorrt_llm/_torch/auto_deploy/distributed/trtllm.py
  tensorrt_llm/_torch/custom_ops/cpp_custom_ops.py
  tensorrt_llm/_torch/distributed/ops.py
  tensorrt_llm/_torch/models/modeling_deepseekv3.py
  tensorrt_llm/_torch/models/modeling_llama.py
  tensorrt_llm/_torch/models/modeling_mixtral.py
  tensorrt_llm/_torch/models/modeling_qwen3_moe.py
  tensorrt_llm/_torch/models/modeling_qwen_moe.py
  tensorrt_llm/_torch/modules/fused_moe.py
  tests/integration/test_lists/test-db/l0_dgx_h100.yml
  tests/integration/test_lists/test-db/l0_h100.yml
  tests/unittest/_torch/multi_gpu_modeling/test_deepseek.py
Labels: Community want to contribute, Community Engagement

#4263 Test: Improve model re-use in C++ DGX tests for CI stability
  cpp/tests/README.md
  cpp/tests/executor/disaggExecutorTest.cpp
  tests/integration/defs/cpp/test_multi_gpu.py
  tests/integration/test_lists/test-db/l0_dgx_h100.yml
Labels: CI

#4371 [AutoDeploy] HF factory improvements
  examples/auto_deploy/.vscode/launch.json
  examples/auto_deploy/.vscode/settings.json
  examples/auto_deploy/README.md
  examples/auto_deploy/simple_config.py
  tensorrt_llm/_torch/auto_deploy/models/factory.py
  tensorrt_llm/_torch/auto_deploy/models/hf.py
  tensorrt_llm/_torch/auto_deploy/shim/demollm.py
  tensorrt_llm/_torch/auto_deploy/shim/interface.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/models/test_hf.py
Labels: AutoDeploy

#4349 feat: add health_generate route to openai serving (Cherry-pick https://github.com/NVIDIA/TensorRT-LLM/pull/3856)
  tensorrt_llm/serve/openai_server.py
  tests/unittest/llmapi/apps/_test_openai_misc.py
Labels: Community want to contribute, Community Engagement

#4410 Scaffoldingllm supports MCP
  examples/scaffolding/contrib/mcp/README.md
  examples/scaffolding/contrib/mcp/e2b/.env
  examples/scaffolding/contrib/mcp/e2b/README.md
  examples/scaffolding/contrib/mcp/e2b/e2bserver.py
  examples/scaffolding/contrib/mcp/e2b/main.py
  examples/scaffolding/contrib/mcp/e2b/pyproject.toml
  examples/scaffolding/contrib/mcp/mcptest.py
  examples/scaffolding/contrib/mcp/weather/pyproject.toml
  examples/scaffolding/contrib/mcp/weather/weather.py
  examples/scaffolding/contrib/mcp/websearch/.env
  examples/scaffolding/contrib/mcp/websearch/README.md
  examples/scaffolding/contrib/mcp/websearch/main.py
  examples/scaffolding/contrib/mcp/websearch/pyproject.toml
  examples/scaffolding/contrib/mcp/websearch/websearch.py
  tensorrt_llm/scaffolding/contrib/__init__.py
  tensorrt_llm/scaffolding/contrib/mcp/__init__.py
  tensorrt_llm/scaffolding/contrib/mcp/chat_handler.py
  tensorrt_llm/scaffolding/contrib/mcp/chat_task.py
  tensorrt_llm/scaffolding/contrib/mcp/mcp_controller.py
  tensorrt_llm/scaffolding/contrib/mcp/mcp_task.py
  tensorrt_llm/scaffolding/contrib/mcp/mcp_utils.py
  tensorrt_llm/scaffolding/contrib/mcp/mcp_worker.py
Labels: Community want to contribute, Community Engagement

#4634 [#4633][doc] Fixed typo in scaffolding README.md
  tensorrt_llm/scaffolding/README.md
Labels: Community want to contribute, Community Engagement

#3209 feature: KV Cache GPUDirect Storage
  cpp/include/tensorrt_llm/batch_manager/kvCacheTransferManager.h
  cpp/include/tensorrt_llm/executor/executor.h
  cpp/include/tensorrt_llm/executor/types.h
  cpp/tensorrt_llm/CMakeLists.txt
  cpp/tensorrt_llm/batch_manager/CMakeLists.txt
  cpp/tensorrt_llm/batch_manager/kvCacheTransferManager.cpp
  cpp/tensorrt_llm/executor/kvCacheRetentionConfig.cpp
  cpp/tensorrt_llm/executor/serialization.cpp
  cpp/tensorrt_llm/pybind/executor/request.cpp
  tensorrt_llm/executor/serialization.py
  tests/unittest/bindings/test_executor_bindings.py
Labels: Community want to contribute, Community Engagement
