Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-06, with the labels that each got.

#4817 [AutoDeploy] Increased Model Coverage Mass Migration Week 2
  examples/auto_deploy/build_and_run_ad.py
  examples/auto_deploy/simple_config.py
  tensorrt_llm/_torch/auto_deploy/custom_ops/_triton_attention_internal.py
  tensorrt_llm/_torch/auto_deploy/custom_ops/flashinfer_attention.py
  tensorrt_llm/_torch/auto_deploy/custom_ops/triton_attention.py
  tensorrt_llm/_torch/auto_deploy/custom_ops/triton_kernels/attention_with_kv_cache.py
  tensorrt_llm/_torch/auto_deploy/models/__init__.py
  tensorrt_llm/_torch/auto_deploy/models/decilm.py
  tensorrt_llm/_torch/auto_deploy/models/deepseek.py
  tensorrt_llm/_torch/auto_deploy/models/factory.py
  tensorrt_llm/_torch/auto_deploy/models/hf.py
  tensorrt_llm/_torch/auto_deploy/models/phi.py
  tensorrt_llm/_torch/auto_deploy/models/qwen3.py
  tensorrt_llm/_torch/auto_deploy/shim/interface.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/attention.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/collectives.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/eliminate_redundant_transposes.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/ep_sharding.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/fused_moe.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/kvcache.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/quantization.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/rope.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/sharding.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tensorrt_llm/_torch/auto_deploy/utils/benchmark.py
  tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/custom_ops/test_moe_ep.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/test_ad_build_small_multi.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_ep_sharding.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/custom_ops/triton_kernels/test_attention_with_kv_cache.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/models/test_hf.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
Labels: AutoDeploy

#4892 [AutoDeploy] deprecate CI post-merge tests and keep them for local testing
  tests/integration/test_lists/test-db/l0_dgx_h200.yml
  tests/integration/test_lists/waives.txt
  tests/unittest/_torch/auto_deploy/integration/test_ad_build.py
  tests/unittest/_torch/auto_deploy/integration/test_lm_eval.py
Labels: AutoDeploy

#4891 [AutoDeploy] _AutoDeployLlmArgs as primary config object
  examples/auto_deploy/.vscode/launch.json
  examples/auto_deploy/README.md
  examples/auto_deploy/build_and_run_ad.py
  examples/auto_deploy/simple_config.py
  tensorrt_llm/_torch/auto_deploy/custom_ops/attention_interface.py
  tensorrt_llm/_torch/auto_deploy/models/hf.py
  tensorrt_llm/_torch/auto_deploy/shim/__init__.py
  tensorrt_llm/_torch/auto_deploy/shim/ad_executor.py
  tensorrt_llm/_torch/auto_deploy/shim/demollm.py
  tensorrt_llm/_torch/auto_deploy/shim/interface.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tensorrt_llm/bench/benchmark/throughput.py
  tensorrt_llm/bench/dataclasses/configuration.py
  tensorrt_llm/bench/dataclasses/reporting.py
  tensorrt_llm/executor/worker.py
  tensorrt_llm/llmapi/llm.py
  tensorrt_llm/llmapi/llm_args.py
  tensorrt_llm/llmapi/llm_utils.py
  tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_engine.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_llm_config.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
Labels: AutoDeploy

#4970 Revert "fix a bug of global cuda graph dummy request"
  examples/pytorch/quickstart_advanced.py
  tensorrt_llm/_torch/pyexecutor/model_engine.py
  tests/integration/defs/test_e2e.py
  tests/integration/test_lists/test-db/l0_dgx_h100.yml
Labels: Community want to contribute

#5006 Edits for tech blog 4
  docs/source/blogs/tech_blog/blog4_Scaling_Expert_Parallelism_in_TensorRT-LLM.md
Labels: Documentation

#4956 Doc: Add info about stop words appearing in output
  docs/source/advanced/gpt-runtime.md
Labels: Documentation, triaged, Community want to contribute

#5190 [TRTLLM-5516] perf: replicate dummy request for cuda graph padding (cherry-pick #4729)
  tensorrt_llm/_torch/pyexecutor/model_engine.py
Labels: Release Blocker

#4972 fix: build_config in TorchLlmArgs and avoid arbitrary args
  examples/auto_deploy/README.md
  examples/auto_deploy/build_and_run_ad.py
  examples/pytorch/quickstart_advanced.py
  tensorrt_llm/_torch/auto_deploy/transformations/transform.py
  tensorrt_llm/_torch/pyexecutor/_util.py
  tensorrt_llm/bench/benchmark/throughput.py
  tensorrt_llm/bench/dataclasses/configuration.py
  tensorrt_llm/builder.py
  tensorrt_llm/commands/serve.py
  tensorrt_llm/llmapi/llm.py
  tensorrt_llm/llmapi/llm_args.py
  tests/integration/defs/disaggregated/test_disaggregated_single_gpu.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/shim/test_llm_config.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/test_ad_build_small_single.py
  tests/unittest/_torch/test_return_logits.py
  tests/unittest/api_stability/references/llm.yaml
  tests/unittest/api_stability/references_committed/llm.yaml
  tests/unittest/llmapi/run_llm_with_postproc.py
  tests/unittest/llmapi/test_llm.py
  tests/unittest/llmapi/test_llm_args.py
  tests/unittest/llmapi/test_llm_pytorch.py
  tests/unittest/llmapi/test_llm_utils.py
Labels: Release Blocker

#5150 doc:add release notes for v0.20.0
  docs/source/release-notes.md
Labels: Release Blocker

#5229 test: Deprecate gpt_model_type "v1" static batching from triton_backend L0_backend_trtllm
  triton_backend/ci/L0_backend_trtllm/custom_metrics_verification_tests.py
  triton_backend/ci/L0_backend_trtllm/test.sh
Labels: Release Blocker

#5298 Revert "[infra] Report CI authorization errors to PR"
  .github/workflows/blossom-ci.yml
Labels: Community want to contribute

#5273 test: correct unittest rerun behavior
  tests/integration/defs/test_unittests.py
Labels: Release Blocker

#5311 Waive L0
  tests/integration/defs/accuracy/test_llm_api_pytorch.py
  tests/integration/test_lists/waives.txt
Labels: Release Blocker

#5317 [Infra]Update 5080 and 5090 case condition since we will upgrade driver
  tests/integration/test_lists/test-db/l0_gb202.yml
  tests/integration/test_lists/test-db/l0_gb203.yml
Labels: Release Blocker

#4771 [feat] Multi-node CI testing support via Slurm
  jenkins/L0_Test.groovy
  jenkins/scripts/slurm_run.sh
  tests/integration/test_lists/test-db/l0_gb200_multi_nodes.yml
Labels: Release Blocker

#3849 feat: AutoDeploy fp8 quantization support for bmm
  tensorrt_llm/_torch/auto_deploy/custom_ops/quant.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/fusion.py
  tensorrt_llm/_torch/auto_deploy/transformations/library/quantization.py
  tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
  tensorrt_llm/_torch/auto_deploy/utils/quantization_utils.py
  tests/unittest/_torch/auto_deploy/_utils_test/_model_test_utils.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/custom_ops/test_quant.py
  tests/unittest/_torch/auto_deploy/unit/singlegpu/transformations/library/test_quantization.py
Labels: triaged, Community want to contribute, AutoDeploy
