Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-08, with the labels that each got.

#6519 [None][infra] Pin the version for triton to 3.3.1 (#6508)
  requirements.txt
Labels: Release Blocker

#6526 [None][fix] Serialize the window_size in the kv event
  tensorrt_llm/_utils.py
  tests/unittest/llmapi/test_llm_kv_cache_events.py
Labels: Community want to contribute

#6391 [None][chore] add online help to build_wheel.py and fix a doc link
  docs/source/performance/perf-analysis.md
  scripts/build_wheel.py
Labels: Documentation, Community want to contribute

#6386 [None][infra] Enable accuracy test for eagle3 and chunked prefill
  docs/source/torch/features/feature_combination_matrix.md
  tests/integration/defs/accuracy/test_llm_api_pytorch.py
  tests/integration/test_lists/test-db/l0_h100.yml
Labels: Community want to contribute

#6476 [TRTLLM-6685][feat] Add speculative metrics for trt llm bench
  tensorrt_llm/bench/dataclasses/reporting.py
  tensorrt_llm/bench/dataclasses/statistics.py
Labels: Community want to contribute

#6013 [None][feat] Add vLLM KV Pool support for XQA kernel
  cpp/kernels/xqa/CMakeLists.txt
  cpp/kernels/xqa/README.md
  cpp/kernels/xqa/defines.h
  cpp/kernels/xqa/mha.cu
  cpp/kernels/xqa/mha.h
  cpp/kernels/xqa/mhaUtils.cuh
  cpp/kernels/xqa/mha_sm90.cu
  cpp/kernels/xqa/tensorMap.cpp
  cpp/kernels/xqa/test/refAttention.h
  cpp/kernels/xqa/test/test.cpp
Labels: Community want to contribute

#6470 [None][feat] Add Qwen3 MoE support to TensorRT backend
  tensorrt_llm/models/__init__.py
  tensorrt_llm/models/qwen/config.py
  tensorrt_llm/models/qwen/convert.py
  tensorrt_llm/models/qwen/model.py
Labels: Community want to contribute

#6603 [TRTLLM-6092][doc] Add LoRA feature usage doc
  docs/source/torch/features/lora.md
Labels: 1.0_doc

#6231 [TRTLLM-6744][feat] Remove input_sf swizzle for module WideEPMoE
  cpp/micro_benchmarks/mixtureOfExpertsBackendBenchmarkFixture.h
  cpp/tensorrt_llm/kernels/cutlass_kernels/include/moe_kernels.h
  cpp/tensorrt_llm/kernels/cutlass_kernels/include/moe_util_kernels.h
  cpp/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_kernels.cu
  cpp/tensorrt_llm/plugins/mixtureOfExperts/mixtureOfExpertsPlugin.cpp
  cpp/tensorrt_llm/thop/moeOp.cpp
  cpp/tensorrt_llm/thop/moeUtilOp.cpp
  cpp/tests/unit_tests/kernels/mixtureOfExpertsTest.cu
  tensorrt_llm/_torch/custom_ops/torch_custom_ops.py
  tensorrt_llm/_torch/modules/fused_moe/fused_moe_cutlass.py
  tensorrt_llm/_torch/modules/fused_moe/fused_moe_wide_ep.py
Labels: SW Architecture

#6626 [None][fix] Fix unnecessary GPU synchronization in torch sampler caused by incorrect tensor reference
  tensorrt_llm/_torch/pyexecutor/sampler.py
Labels: Community want to contribute

#6739 [None][doc] Add doc for multimodal feature support matrix (#6619)
  docs/source/reference/multimodal-feature-support-matrix.md
Labels: 1.0_doc

#6653 [None][fix] Remove lock related typo in py_executor
  tensorrt_llm/_torch/pyexecutor/executor_request_queue.py
  tensorrt_llm/_torch/pyexecutor/py_executor.py
Labels: Community want to contribute

#6528 [None][doc] Move AutoDeploy README.md to torch docs
  docs/source/media/ad_overview.png
  docs/source/torch.md
  docs/source/torch/auto_deploy/advanced/benchmarking_with_trtllm_bench.md
  docs/source/torch/auto_deploy/advanced/example_run.md
  docs/source/torch/auto_deploy/advanced/expert_configurations.md
  docs/source/torch/auto_deploy/advanced/logging.md
  docs/source/torch/auto_deploy/advanced/workflow.md
  docs/source/torch/auto_deploy/auto-deploy.md
  docs/source/torch/auto_deploy/support_matrix.md
Labels: 1.0_doc

#5785 [None][feat] Core Metrics Implementation
  requirements.txt
  tensorrt_llm/_torch/pyexecutor/llm_request.py
  tensorrt_llm/_utils.py
  tensorrt_llm/executor/postproc_worker.py
  tensorrt_llm/executor/result.py
  tensorrt_llm/executor/worker.py
  tensorrt_llm/llmapi/llm.py
  tensorrt_llm/llmapi/llm_args.py
  tensorrt_llm/metrics/__init__.py
  tensorrt_llm/metrics/collector.py
  tensorrt_llm/metrics/enums.py
  tensorrt_llm/serve/openai_server.py
  tests/integration/defs/test_e2e.py
  tests/integration/test_lists/test-db/l0_a10.yml
  tests/unittest/api_stability/references/llm.yaml
  tests/unittest/api_stability/references/request_output.yaml
  tests/unittest/llmapi/apps/_test_openai_prometheus.py
  tests/unittest/llmapi/test_llm_pytorch.py
Labels: Community want to contribute

#6592 [TRTLLM-6823][doc] Add checkpoint refactor docs
  docs/source/torch/features/checkpoint_loading.md
  tensorrt_llm/_torch/models/checkpoints/base_checkpoint_loader.py
  tensorrt_llm/_torch/pyexecutor/model_engine.py
Labels: 1.0_doc

#6745 [TRTLLM-6906][chore] Using pybind to bind functions in thop/attentionOp
  cpp/tensorrt_llm/nanobind/CMakeLists.txt
  cpp/tensorrt_llm/nanobind/bindings.cpp
  cpp/tensorrt_llm/nanobind/thop/bindings.cpp
  cpp/tensorrt_llm/nanobind/thop/bindings.h
  cpp/tensorrt_llm/pybind/CMakeLists.txt
  cpp/tensorrt_llm/pybind/bindings.cpp
  cpp/tensorrt_llm/pybind/thop/bindings.cpp
  cpp/tensorrt_llm/pybind/thop/bindings.h
  cpp/tensorrt_llm/thop/attentionOp.cpp
  cpp/tensorrt_llm/thop/attentionOp.h
  tensorrt_llm/_torch/attention_backend/trtllm.py
Labels: Community want to contribute

#6860 [https://nvbugs/5445466][fix] fix deepseek r1 hang by not enabling mnnvl by default
  tensorrt_llm/_torch/distributed/ops.py
  tests/integration/test_lists/waives.txt
Labels: weekly_release_blocker

#6882 [https://nvbugs/5450262][fix] Fix unsupported alltoall use case
  tensorrt_llm/_torch/modules/fused_moe/fused_moe_cutlass.py
  tests/integration/test_lists/waives.txt
  tests/unittest/_torch/multi_gpu_modeling/test_llama4.py
Labels: weekly_release_blocker

#5521 [None] [feat] Add Tencent HunYuanMoEV1 model support
  examples/llm-api/quickstart_advanced.py
  tensorrt_llm/_torch/attention_backend/interface.py
  tensorrt_llm/_torch/model_config.py
  tensorrt_llm/_torch/models/__init__.py
  tensorrt_llm/_torch/models/modeling_hunyuan_moe.py
  tensorrt_llm/_torch/modules/attention.py
  tensorrt_llm/_torch/pyexecutor/config_utils.py
  tensorrt_llm/functional.py
  tensorrt_llm/llmapi/tokenizer.py
Labels: Community want to contribute, Community Engagement

#6723 [None][fix] Fix the issue of responsibility boundary between the assert and tllmException files
  cpp/include/tensorrt_llm/common/assert.h
  cpp/include/tensorrt_llm/common/tllmException.h
Labels: Community want to contribute

#6764 [None][test] Add accuracy evaluation for AutoDeploy
  tensorrt_llm/_torch/auto_deploy/llm_args.py
  tests/integration/defs/accuracy/accuracy_core.py
  tests/integration/defs/accuracy/test_llm_api_autodeploy.py
Labels: Community want to contribute

#6758 [None][fix] Fix: Using RAII to automatically manage the allocation and release of va_list for potential resource leak
  cpp/include/tensorrt_llm/common/stringUtils.h
  cpp/tensorrt_llm/common/stringUtils.cpp
Labels: Community want to contribute

#6767 [TRTLLM-6341][chore] Preliminary refactors on the kv cache manager before supporting swa kv cache reuse
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tensorrt_llm/batch_manager/kvCacheManager.cpp
  cpp/tests/unit_tests/batch_manager/capacitySchedulerTest.cpp
  cpp/tests/unit_tests/batch_manager/kvCacheManagerTest.cpp
  cpp/tests/unit_tests/batch_manager/kvCacheUtilsTest.cpp
  cpp/tests/unit_tests/batch_manager/llmRequestTest.cpp
Labels: KV-Cache Management

#7056 [None][doc] update v1.0 doc for trtllm-serve
  docs/source/commands/trtllm-serve/trtllm-serve.rst
Labels: 1.0_doc

#7101 [None][doc] Update gpt-oss deployment guide to latest release image
  README.md
  docs/source/blogs/tech_blog/blog9_Deploying_GPT_OSS_on_TRTLLM.md
Labels: Community want to contribute

#7182 [None][fix] Switch llm api quickstart example location per workflow.
  examples/llm-api/_tensorrt_engine/quickstart_example.py
  examples/llm-api/quickstart_example.py
Labels: 1.0_doc

#7197 [None][doc] add LoRA to feature combination matrix
  docs/source/1.0/features/feature-combination-matrix.md
  docs/source/1.0/features/multi-modality.md
Labels: 1.0_doc

#6972 [TRTLLM-6342][feat] TP Sharding read from the model config
  tensorrt_llm/_torch/auto_deploy/config/default.yaml
  tensorrt_llm/_torch/auto_deploy/llm_args.py
  tensorrt_llm/_torch/auto_deploy/models/factory.py
  tensorrt_llm/_torch/auto_deploy/models/hf.py
  tensorrt_llm/_torch/auto_deploy/transform/library/sharding.py
  tensorrt_llm/_torch/auto_deploy/utils/node_utils.py
  tensorrt_llm/_torch/auto_deploy/utils/sharding_utils.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_bmm_sharding.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_ep_sharding.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_tp_sharding.py
Labels: AutoDeploy

#5804 [TRTLLM-6081] doc: KV cache feature documentation
  docs/source/1.0/features/kvcache.md
Labels: 1.0_doc

#7276 [None][doc] add runtime optimizations for overview doc
  docs/source/1.0/architecture/overview.md
Labels: 1.0_doc

#7228 [None][feat] KV Cache Connector API
  cpp/include/tensorrt_llm/batch_manager/kvCacheConnector.h
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tensorrt_llm/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/nanobind/CMakeLists.txt
  cpp/tensorrt_llm/nanobind/batch_manager/kvCacheConnector.cpp
  cpp/tensorrt_llm/nanobind/batch_manager/kvCacheConnector.h
  cpp/tensorrt_llm/nanobind/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/nanobind/bindings.cpp
  cpp/tensorrt_llm/pybind/CMakeLists.txt
  cpp/tensorrt_llm/pybind/batch_manager/bindings.cpp
  cpp/tensorrt_llm/pybind/batch_manager/kvCacheConnector.cpp
  cpp/tensorrt_llm/pybind/batch_manager/kvCacheConnector.h
  cpp/tensorrt_llm/pybind/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/pybind/bindings.cpp
  cpp/tensorrt_llm/runtime/torch.h
  examples/llm-api/llm_kv_cache_connector.py
  tensorrt_llm/_torch/pyexecutor/_util.py
  tensorrt_llm/_torch/pyexecutor/kv_cache_connector.py
  tensorrt_llm/_torch/pyexecutor/py_executor.py
  tensorrt_llm/_torch/pyexecutor/py_executor_creator.py
  tensorrt_llm/_torch/pyexecutor/resource_manager.py
  tensorrt_llm/executor/executor.py
  tensorrt_llm/executor/proxy.py
  tensorrt_llm/executor/worker.py
  tensorrt_llm/llmapi/llm.py
  tensorrt_llm/llmapi/llm_args.py
  tests/integration/defs/llmapi/test_llm_api_connector.py
  tests/integration/defs/llmapi/test_llm_examples.py
  tests/integration/test_lists/test-db/l0_a10.yml
  tests/unittest/_torch/test_connector.py
  tests/unittest/api_stability/references/llm.yaml
Labels: Community want to contribute

#7137 [None][docs] Update Dynasor paper info
  tensorrt_llm/scaffolding/contrib/Dynasor/README.md
Labels: Community want to contribute, waiting for feedback
