Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-07, with the labels that each got.

#5404 [#5403][perf] Conditionally enable SWAP AB for speculative decoding
  cpp/kernels/xqa/defines.h
  cpp/kernels/xqa/mha.cu
  cpp/kernels/xqa/mha_sm90.cu
  cpp/kernels/xqa/test/test.cpp
Labels: Community want to contribute

#3922 feat:[AutoDeploy] E2E build example for llama4 VLM
  tests/unittest/_torch/auto_deploy/integration/test_llama4_vlm_export.py
Labels: AutoDeploy

#5115 feat: support more parameters in openai worker of scaffolding
  tensorrt_llm/scaffolding/task.py
  tensorrt_llm/scaffolding/worker.py
Labels: Community want to contribute, Scaffolding

#5676 [TRTLLM-6100] fix: Nvbug 5356427: autotuned TRTLLM Gen fp8 block scale MoE illegal memory access
  cpp/tensorrt_llm/thop/fp8BlockScaleMoe.cpp
  tensorrt_llm/_torch/custom_ops/trtllm_gen_custom_ops.py
Labels: bug

#5681 [fix] improve fp4_block_scale_moe_runner type check
  cpp/tensorrt_llm/thop/fp4BlockScaleMoe.cpp
Labels: Community want to contribute, Community Engagement

#5650 [feat] Add TensorRT-Engine Qwen3 (dense) model support
  tensorrt_llm/models/__init__.py
  tensorrt_llm/models/qwen/config.py
  tensorrt_llm/models/qwen/convert.py
  tensorrt_llm/models/qwen/model.py
Labels: Community want to contribute, Community Engagement

#4028 feat:enable kvcache to be reused during request generation
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tensorrt_llm/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/batch_manager/trtGptModelInflightBatching.cpp
  cpp/tensorrt_llm/batch_manager/trtGptModelInflightBatching.h
  cpp/tests/executor/executorTest.cpp
Labels: triaged, Community want to contribute, Community Engagement

#5020 fix #4974: A thread leak issue in scaffolding unittest
  tests/unittest/scaffolding/test_bench.py
Labels: Community want to contribute

#5982 BlockManager copy constructor fix
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tests/unit_tests/batch_manager/kvCacheManagerTest.cpp
Labels: Community want to contribute

#6255 Add register_fake for finegrained_mixed_dtype_gemm torch_op
  tensorrt_llm/_torch/custom_ops/torch_custom_ops.py
Labels: Community want to contribute

#5354 [feat]: support logit_bias
  tensorrt_llm/sampling_params.py
  tensorrt_llm/serve/openai_protocol.py
  tests/integration/test_lists/test-db/l0_a10.yml
  tests/unittest/llmapi/apps/_test_openai_chat.py
  tests/unittest/llmapi/apps/_test_openai_completions.py
Labels: Community want to contribute

#6340 [fix] README link directs to intended doc
  examples/models/core/llama4/README.md
Labels: Documentation, Community want to contribute

#6356 doc: Add README for wide EP
  docs/source/blogs/tech_blog/blog4_Scaling_Expert_Parallelism_in_TensorRT-LLM.md
  examples/disaggregated/slurm/gen_yaml.py
  examples/disaggregated/slurm/submit.sh
  examples/wide_ep/README.md
  examples/wide_ep/slurm_scripts/submit.sh
Labels: Documentation

#6344 [FIX] fix bugs caused by None attention_bias during Qwen3 model convert engine
  tensorrt_llm/models/qwen/config.py
  tensorrt_llm/models/qwen/convert.py
Labels: Community want to contribute

#6418 chore: add trtllm-serve json schema example into doc.
  examples/serve/openai_completion_client_json_schema.py
  tests/unittest/llmapi/apps/_test_openai_chat_json.py
  tests/unittest/llmapi/apps/_test_trtllm_serve_example.py
Labels: Documentation

#6441 [doc] update the doc of feature combination matrix
  docs/source/torch/features/feature_combination_matrix.md
Labels: Documentation

#6004 [PERF] Move calculation Qwen2-VL's rotary_cos_sin to LLM worker process
  tensorrt_llm/_torch/models/modeling_qwen2vl.py
Labels: Community want to contribute

#6270 [doc] Update perf_overview.md for release 0.21
  docs/source/performance/perf-overview.md
Labels: Documentation
