Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-04, with the labels that each got.

#3162 doc: update main readme
  README.md
Labels: Documentation

#3017 fix: segfault in cudaDriverWrapper
  cpp/tensorrt_llm/common/cudaDriverWrapper.cpp
  cpp/tensorrt_llm/common/cudaDriverWrapper.h
  cpp/tensorrt_llm/kernels/decoderMaskedMultiheadAttention/decoderXQAImplJIT/cubinObjRegistry.h
  cpp/tests/unit_tests/common/CMakeLists.txt
  cpp/tests/unit_tests/common/cudaDriverWrapperTest.cpp
Labels: bug

#3238 Fix torch nvsmall through pyexecutor and fix its TP support
  tensorrt_llm/_torch/models/modeling_nvsmall.py
Labels: bug

#3226 fix: runtime error in test_deepseek_allreduce.py
  tests/unittest/_torch/multi_gpu/test_deepseek_allreduce.py
Labels: bug

#3276 fix: #3137 speculative decoding and multimodal input support
  tensorrt_llm/layers/embedding.py
Labels: Community want to contribute, Community Engagement

#3413 fix: fix partialMatch
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tests/batch_manager/CMakeLists.txt
  cpp/tests/batch_manager/blockKeyTest.cpp
Labels: Community want to contribute, Community Engagement

#3527 feat: Add stream generation task scaffolding examples
  examples/scaffolding/contrib/AsyncGeneration/README.md
  examples/scaffolding/contrib/AsyncGeneration/stream_generation_controller.py
  examples/scaffolding/contrib/AsyncGeneration/stream_generation_run.py
  examples/scaffolding/contrib/AsyncGeneration/stream_generation_task.py
  examples/scaffolding/contrib/__init__.py
Labels: Community want to contribute, Community Engagement

#3501 feat: Add Dynasor-CoT in scaffolding examples
  examples/scaffolding/contrib/Dynasor/README.md
  examples/scaffolding/contrib/Dynasor/__init__.py
  examples/scaffolding/contrib/Dynasor/dynasor_controller.py
  examples/scaffolding/contrib/Dynasor/evaluator.py
  examples/scaffolding/contrib/Dynasor/scaffolding_dynasor_run.py
  examples/scaffolding/contrib/__init__.py
Labels: Community want to contribute, Community Engagement

#3768 chore: Move opencv-python import inside load_video() function
  tensorrt_llm/inputs/utils.py
Labels: Community want to contribute

#3631 fix: 5197419 and removed unused runtime kernels
  cpp/tensorrt_llm/batch_manager/createNewDecoderRequests.cpp
  cpp/tensorrt_llm/runtime/runtimeKernels.cu
  cpp/tensorrt_llm/runtime/runtimeKernels.h
  cpp/tensorrt_llm/runtime/utils/sessionUtils.cpp
  cpp/tensorrt_llm/runtime/utils/sessionUtils.h
  cpp/tests/runtime/gptDecoderBatchedTest.cpp
  cpp/tests/unit_tests/kernels/sampling/samplingUtilsTest.cu
  cpp/tests/unit_tests/runtime/runtimeKernelTest.cpp
Labels: bug, CI

#3797 [doc] Better document for Draft-Target-Model (DTM) speculative decoding
  examples/draft_target_model/README.md
Labels: Documentation

#3845 feat: Mistral-Large-2 support in the Pytorch workflow
  tensorrt_llm/_torch/models/__init__.py
  tensorrt_llm/_torch/models/modeling_mistral.py
Labels: new model, LLM API/Workflow
