Repository NVIDIA/TensorRT-LLM, pull requests merged in 2025-09, with the labels that each got.

#7378 [None][Doc] Polish parallelism doc and add wide ep sectionwq.
  docs/source/1.0/features/parallel-strategy.md
Labels: 1.0_doc

#6740 [None][doc] add blackwell information into support matrix
  docs/source/overview.md
  docs/source/reference/support-matrix.md
Labels: 1.0_doc

#7389 [TRTLLM-6342][fix] Fixed triggering BMM sharding
  tensorrt_llm/_torch/auto_deploy/config/default.yaml
  tensorrt_llm/_torch/auto_deploy/llm_args.py
  tests/unittest/_torch/auto_deploy/unit/multigpu/transformations/library/test_bmm_sharding.py
Labels: bug, AutoDeploy

#7502 [None][fix] fix hunyuan_moe init bug
  tensorrt_llm/_torch/models/modeling_hunyuan_moe.py
  tensorrt_llm/_torch/pyexecutor/config_utils.py
Labels: Community want to contribute

#7382 [TRTLLM-6081][Doc] Address review concerns
  docs/source/1.0/examples/kvcacheconfig.md
  docs/source/1.0/examples/kvcacheretentionconfig.md
  docs/source/1.0/features/kvcache.md
  docs/source/1.0/features/speculative-decoding.md
Labels: 1.0_doc

#7490 [#3325][feat] Add MCTS and TOT tree-based inference controllers to Scaffolding
  examples/scaffolding/contrib/TreeInference/run_mcts_example.py
  examples/scaffolding/contrib/TreeInference/run_tot_example.py
  tensorrt_llm/scaffolding/__init__.py
  tensorrt_llm/scaffolding/contrib/TreeInference/README_TREE_METHODS.md
  tensorrt_llm/scaffolding/contrib/TreeInference/tree_controllers.py
Labels: Community want to contribute

#7252 [None][docs] refine docs for accuracy evaluation of gpt-oss models
  docs/source/deployment-guide/quick-start-recipe-for-gpt-oss-on-trtllm.md
Labels: Community want to contribute, waiting for feedback

#5488 [None][feat] Nixl support for GDS
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/include/tensorrt_llm/batch_manager/kvCacheTransferManager.h
  cpp/include/tensorrt_llm/executor/executor.h
  cpp/include/tensorrt_llm/executor/transferAgent.h
  cpp/tensorrt_llm/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/batch_manager/kvCacheTransferManager.cpp
  cpp/tensorrt_llm/executor/cache_transmission/nixl_utils/CMakeLists.txt
  cpp/tensorrt_llm/executor/cache_transmission/nixl_utils/transferAgent.cpp
  cpp/tensorrt_llm/executor/cache_transmission/nixl_utils/transferAgent.h
  cpp/tensorrt_llm/executor/kvCacheRetentionConfig.cpp
  cpp/tensorrt_llm/executor/serialization.cpp
  cpp/tensorrt_llm/nanobind/executor/request.cpp
  cpp/tensorrt_llm/pybind/executor/request.cpp
  cpp/tests/unit_tests/batch_manager/kvCacheManagerTest.cpp
  cpp/tests/unit_tests/executor/transferAgentTest.cpp
  jenkins/Build.groovy
Labels: Community want to contribute

#7178 [#6529][feat] CMake option to link statically with cublas/curand
  cpp/CMakeLists.txt
Labels: Community want to contribute

#6874 [#6798][fix] fix compilation error in ub_allocator in single device build
  .gitignore
  cpp/tensorrt_llm/kernels/userbuffers/ub_allocator.h
Labels: Community want to contribute

#7383 [None][feat] Use a shell context to install dependancies
  .gitignore
  docker/Dockerfile.multi
  docker/common/install.sh
  docs/source/installation/build-from-source-linux.md
  enroot/Makefile
  jenkins/current_image_tags.properties
Labels: Community want to contribute

#7751 [None][doc] Enhance api reference doc by labeling stable APIs
  docs/source/_static/custom.css
  docs/source/helper.py
  tensorrt_llm/llmapi/utils.py
Labels: Release Blocker, 1.0_doc

#7768 [https://nvbugs/5517023][fix] Pass allreduce strategy and force NCCL on pre-Blackwell arch
  tensorrt_llm/_torch/models/modeling_llama.py
Labels: Release Blocker

#7717 [https://nvbugs/5516710][fix] fix Llama 3.3 TP PP case
  tensorrt_llm/_torch/models/modeling_llama.py
  tensorrt_llm/_torch/models/modeling_llama_min_latency.py
  tests/integration/test_lists/test-db/l0_dgx_b200.yml
  tests/unittest/_torch/multi_gpu_modeling/test_llama3.py
Labels: Release Blocker

#7747 [https://nvbugs/5481434][feat] cherry-pick fix to reuse pytorch memory segments occupied by cudagraph
  tensorrt_llm/_torch/modules/fused_moe/fused_moe_deepgemm.py
Labels: Cherry-pick

#2382 [None][fix] fix load_model_on_cpu on qwen/convert_checkpoint.py
  examples/models/core/qwen/convert_checkpoint.py
Labels: triaged, feature request, Community want to contribute, waiting for feedback

#7727 [TRTLLM-7008][fix] cherrypick to main Add automatic shared memory delete if already exist
  examples/wide_ep/README.md
  tensorrt_llm/_torch/modules/fused_moe/moe_load_balancer.py
  tests/integration/test_lists/waives.txt
Labels: Cherry-pick

#7854 [None][fix] cherrypick to main: Fix possible mpi broadcast and gather issue on large object
  tensorrt_llm/_torch/distributed/communicator.py
Labels: Cherry-pick

#7848 [None][doc] Update Perf-Overview.md for release/1.0
  docs/source/performance/perf-overview.md
Labels: Doc, Release Blocker

#7863 [None][doc] add stable label to all the un-labelled arguments in LLM class
  tensorrt_llm/llmapi/utils.py
Labels: Release Blocker

#7861 [None][fix] api stability bug in status label
  tensorrt_llm/llmapi/llm_args.py
  tests/unittest/api_stability/api_stability_core.py
Labels: Release Blocker

#7855 [https://nvbugs/5525849][fix] Cherry-pick to fix mismatch of max seq len between kv cache manager and dummy requests
  tensorrt_llm/_torch/pyexecutor/_util.py
Labels: Cherry-pick

#6768 [TRTLLM-6341][feature] Support SWA KV cache reuse
  cpp/include/tensorrt_llm/batch_manager/kvCacheManager.h
  cpp/tensorrt_llm/batch_manager/kvCacheManager.cpp
  cpp/tensorrt_llm/batch_manager/trtGptModelInflightBatching.cpp
  cpp/tensorrt_llm/nanobind/batch_manager/kvCacheManager.cpp
  cpp/tests/unit_tests/batch_manager/cacheTransBufferTest.cpp
  cpp/tests/unit_tests/batch_manager/capacitySchedulerTest.cpp
  cpp/tests/unit_tests/batch_manager/kvCacheManagerTest.cpp
  cpp/tests/unit_tests/executor/agentCommTest.cpp
  cpp/tests/unit_tests/multi_gpu/cacheTransceiverTest.cpp
  examples/models/core/llama/summarize_long.py
  examples/models/core/qwen2audio/utils.py
  examples/utils.py
  tensorrt_llm/_torch/pyexecutor/_util.py
  tensorrt_llm/functional.py
  tests/integration/defs/accuracy/test_llm_api_pytorch.py
  tests/integration/test_lists/test-db/l0_h100.yml
Labels: KV-Cache Management

#7496 [None][feat] add model seed-oss
  tensorrt_llm/_torch/models/__init__.py
  tensorrt_llm/_torch/models/modeling_seedoss.py
Labels: Community want to contribute
